{% set name = "lowbar" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lowbar-{{ version }}.tar.gz
  sha256: 61af91bb5a345823c0728aab435e2a1354dd454927e8d0897d2ecd77135290de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - lowbar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/lowbar/
  summary: The simplest no-nonsense progress bar for python.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
